blog/applications/entrada/urls.py
from django.urls import path
from . import views

app_name = "entrada_app"

urlpatterns = [
    path('entradas/', views.EntryListView.as_view(), name='entry-list'),
    path('entradas/<slug>/', views.EntryDetailView.as_view(), name='entry-detail')
]

blog/applications/favoritos/urls.py
from django.urls import path
from . import views

app_name = "favoritos_app"

urlpatterns = [
    path('perfil/', views.UserFavoriteView.as_view(), name='perfil'),
    path('perfil/<int:id>/', views.AddFavoriteView.as_view(), name='add-favorite'),
    path('perfil/delete-favorite/<int:id>/', views.FavoritesDeteleView.as_view(), name='delete-favorite')
]

blog/applications/home/urls.py
#
from django.urls import path
from . import views

app_name = "home_app"

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('contact/', views.ContactCreateView.as_view(), name='contact-create')
]

blog/applications/users/urls.py
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user-register'),
    path('login/', views.LoginUser.as_view(), name='user-login'),
    path('logout/', views.LogoutView.as_view(), name='user-logout'),
    path('update/', views.UpdatePasswordView.as_view(), name='user-update')
]

blog/blog/urls.py
"""
Proyecto Curso Django
"""
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from applications.home.sitemap import EntrySitemap, Sitemap

urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entrada.urls')),
    re_path('', include('applications.favoritos.urls')),
    #URLS CKEDITOR
    path(r'^ckedtior/', include('ckeditor_uploader.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

sitemaps = {

    'site': Sitemap(
        [
            'home_app:index'
        ]
    ),
    'entradas': EntrySitemap
}

urlpatterns_sitemap = [

    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')

]

urlpatterns = urlpatterns_main + urlpatterns_sitemap

blog/templates/includes/footer.html
<footer class="py-2 my-2">
  <!-- <ul class="nav justify-content-center border-bottom pb-3 mb-3">
    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
  </ul> -->
  <p class="text-center text-body-secondary">© 2023 Blog CH, Inc</p>
</footer>

blog/templates/includes/formulario-contacto.html
<div class="row" style="background-color: #EEEEEE;">
    <div class="col-md-2"></div>
    <div class="col-md-8 mt-3 mb-3">
        <h5>Formulario Contacto</h5>
        <hr>
        <form method="post" action="{% url 'home_app:contact-create' %}">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6">
                    <label for="full_name" class="form-label">Nombres</label>
                    <input type="text" class="form-control" name="full_name" id="id_full_name" placeholder="Nombres" required>
                </div>
                <div class="col-md-6">
                    <label for="email" class="form-label">Correo</label>
                    <input type="email" class="form-control" name="email" id="id_email" placeholder="Correo" required>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-md-12">
                    <label for="message" class="form-label">Mensaje</label>
                    <textarea class="form-control" name="message" id="id_message" placeholder="Mensaje" required></textarea>
                </div>
            </div>
            <br>
            <center><button type="submit" class="btn btn-success">Enviar</button></center>
        </form>
        <hr>
        <h5>Otras formas de Contacto</h5>
        <div class="row">
            <div class="col-md-6">
                <label>Telefono: </label>
                <span class="badge bg-info text-white">{{ phone }}</span>
            </div>
            <div class="col-md-6">
                <label>Correo: </label>
                <span class="badge bg-info text-white">{{ correo }}</span>
            </div>
        </div>
    </div>
    <div class="col-md-2"></div>

</div>

blog/templates/includes/header.html
<nav class="navbar navbar-expand-lg navbar-light mb-4 shadow" style="background-color: #EEEEEE;">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home_app:home' %}">Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home_app:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'entrada_app:entry-list' %}">Blog</a>
                </li>
                <li class="nav-item">

                    {% if not user.is_anonymous %}

                        <a class="btn btn-outline-info" href="{% url 'favoritos_app:perfil' %}">Perfil</a>

                    {% else %}

                        <a class="btn btn-outline-success" href="{% url 'users_app:user-login' %}">Acceder</a>

                    {% endif %}

                    
                </li>
                <!-- <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">Dropdown link</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li> -->
            </ul>
        </div>

    </div>
</nav>