blog/applications/users/urls.py
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user-register'),
    path('login/', views.LoginUser.as_view(), name='user-login'),
    path('logout/', views.LogoutView.as_view(), name='user-logout'),
    path('update/', views.UpdatePasswordView.as_view(), name='user-update')
]

blog/blog/urls.py
"""
Proyecto Curso Django
"""
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from applications.home.sitemap import EntrySitemap, Sitemap

urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entrada.urls')),
    re_path('', include('applications.favoritos.urls')),
    #URLS CKEDITOR
    path(r'^ckedtior/', include('ckeditor_uploader.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

sitemaps = {

    'site': Sitemap(
        [
            'home_app:index'
        ]
    ),
    'entradas': EntrySitemap
}

urlpatterns_sitemap = [

    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')

]

urlpatterns = urlpatterns_main + urlpatterns_sitemap

blog/applications/users/models.py
from django.db import models

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
#
from .managers import UserManager

class User(AbstractBaseUser, PermissionsMixin):

    GENDER_CHOICES = (
        ('M', 'Masculino'),
        ('F', 'Femenino'),
        ('O', 'Otros'),
    )

    email = models.EmailField(unique=True)
    full_name = models.CharField('Nombres', max_length=100)
    ocupation = models.CharField(
        'Ocupacion',
        max_length=30, 
        blank=True
    )
    genero = models.CharField(
        max_length=1, 
        choices=GENDER_CHOICES, 
        blank=True
    )
    date_birth = models.DateField(
        'Fecha de nacimiento', 
        blank=True,
        null=True
    )
    #
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = ['full_name']

    objects = UserManager()

    def get_short_name(self):
        return self.email
    
    def get_full_name(self):
        return self.full_name

blog/applications/users/forms.py
from django import forms
from django.contrib.auth import authenticate
#
from .models import User

class UserRegisterForm(forms.ModelForm):

    password1 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Contraseña', 'class': 'form-control'
            }
        )
    )
    password2 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Repetir Contraseña', 'class': 'form-control'
            }
        )
    )

    class Meta:
        """Meta definition for Userform."""

        model = User
        fields = (
            'email',
            'full_name',
            'ocupation',
            'genero',
            'date_birth',
        )

        widgets = {
            'email' : forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Correo Electronico'}),
            'full_name': forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Nombres y Apellidos'}),
            'ocupation': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ocupacion'}),
            'genero': forms.Select(attrs={'class':'form-control'}),
            'date_birth': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'})
        }
    
    def clean_password2(self):
        if self.cleaned_data['password1'] != self.cleaned_data['password2']:
            self.add_error('password2', 'Las contraseñas no son iguales')


class LoginForm(forms.Form):
    email = forms.CharField(
        label='E-mail',
        required=True,
        widget=forms.EmailInput(
            attrs={
                'placeholder': 'Correo Electronico', 'class': 'form-control'
            }
        )
    )
    password = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Contraseña', 'class': 'form-control'
            }
        )
    )

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        email = self.cleaned_data['email']
        password = self.cleaned_data['password']

        if not authenticate(email=email, password=password):
            raise forms.ValidationError('Los datos de usuario no son correctos')
        
        return self.cleaned_data


class UpdatePasswordForm(forms.Form):

    password1 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Contraseña Actual'
            }
        )
    )
    password2 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Contraseña Nueva'
            }
        )
    )

blog/applications/users/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.urls import reverse_lazy, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect

from django.views.generic import (
    View,
    CreateView
)

from django.views.generic.edit import (
    FormView
)

from .forms import (
    UserRegisterForm, 
    LoginForm,
    UpdatePasswordForm,
)
#
from .models import User
# 


class UserRegisterView(FormView):
    template_name = 'users/register.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy('users_app:user-login')

    def form_valid(self, form):
        #
        User.objects.create_user(
            form.cleaned_data['email'],
            form.cleaned_data['password1'],
            full_name = form.cleaned_data['full_name'],
            ocupation=form.cleaned_data['ocupation'],
            genero=form.cleaned_data['genero'],
            date_birth=form.cleaned_data['date_birth'],
        )
        # enviar el codigo al email del user
        return super(UserRegisterView, self).form_valid(form)



class LoginUser(FormView):
    template_name = 'users/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('favoritos_app:perfil')

    def form_valid(self, form):
        user = authenticate(
            email=form.cleaned_data['email'],
            password=form.cleaned_data['password']
        )
        login(self.request, user)
        return super(LoginUser, self).form_valid(form)


class LogoutView(View):

    def get(self, request, *args, **kargs):
        logout(request)
        return HttpResponseRedirect(
            reverse(
                'users_app:user-login'
            )
        )


class UpdatePasswordView(LoginRequiredMixin, FormView):
    template_name = 'users/update.html'
    form_class = UpdatePasswordForm
    success_url = reverse_lazy('users_app:user-login')
    login_url = reverse_lazy('users_app:user-login')

    def form_valid(self, form):
        usuario = self.request.user
        user = authenticate(
            email=usuario.email,
            password=form.cleaned_data['password1']
        )

        if user:
            new_password = form.cleaned_data['password2']
            usuario.set_password(new_password)
            usuario.save()

        logout(self.request)
        return super(UpdatePasswordView, self).form_valid(form)

blog/templates/users/base_users.html
{% extends "base.html" %}

{% load  static %}

{% block css %}

{% endblock css %}

{% block js %}

{% endblock js %}

blog/templates/users/login.html
{% extends "entrada/base_entrada.html" %}

{% load static %}


{% block content %}

<div class="container">
    <div class="row mt-5">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="card shadow-lg mb-3">
                <div class="row g-0">
                    <div class="col-md-6">
                        <img src="{% static 'img/blog.jpg' %}" class="img-fluid rounded-start" alt="...">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <h5 class="card-title"><center><h5>Acceder <b>MyBlog</b></h5></center></h5>
                            <hr>
                            <form method="post" enctype="multipart/form-data" action="{% url 'users_app:user-login' %}">
                                {% csrf_token %}

                                <label for="email" class="form-label">Email</label>
                                {{ form.email}}
                                
                                <br>

                                <label for="password" class="form-label">Contraseña</label>
                                {{ form.password}}

                                <div class="d-grid gap-2 mt-3">
                                    <button type="submit" class="btn btn-outline-success btn-block">Ingresar</button>
                                    <a href="{% url 'users_app:user-register' %}" class="btn btn-outline-primary">Registrarse</a>
                                </div>
                            </form>
                            {% if form.errors %}

                                <div class="alert alert-warning alert-dismissible fade show mt-3" role="alert">
                                    {% for field, error_msgs in form.errors.items %}
                                        {% for error_msg in error_msgs %}
                                            <p>{{ error_msg }}</p>
                                        {% endfor %}
                                    {% endfor %}
                                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                </div>

                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
    
        
</div>


{% endblock content %}

blog/templates/users/register.html
{% extends "entrada/base_entrada.html" %}

{% load static %}


{% block content %}

<div class="container">
    <div class="row mt-5">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="card shadow-lg">
                <div class="card-header bg-primary text-white">
                    <center><h5>Registrarse</h5></center>
                </div>
                <div class="card-body">
                    <form method="post" action="{% url 'users_app:user-register' %}" enctype="multipart/form-data">
                        {% csrf_token %}

                        {% if form.password2.errors %}

                            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                {{ form.password2.errors }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>

                        {% endif %}

                        <div class="row">
                            <div class="col-sm-12 col-md-12 mb-1">
                                <label for="email" class="form-label">Email</label>
                                {{ form.email }}
                            </div>
                            <div class="col-sm-12 col-md-6 mb-1">
                                <label for="full_name" class="form-label">Nombres</label>
                                {{ form.full_name }}
                            </div>
                            <div class="col-sm-12 col-md-6 mb-1">
                                <label for="id_ocupation" class="form-label">Ocupacion</label>
                                {{ form.ocupation }}
                            </div>
                            <div class="col-sm-12 col-md-6 mb-1">
                                <label for="id_genero" class="form-label">Genero</label>
                                {{ form.genero }}
                            </div>
                            <div class="col-sm-12 col-md-6 mb-1">
                                <label for="fecha_nacimiento" class="form-label">Fecha Nacimiento</label>
                                {{ form.date_birth }}
                            </div>
                            <div class="col-sm-12 col-md-12 mb-1">
                                <label for="password1" class="form-label">Contraseña</label>
                                {{ form.password1 }}
                            </div>
                            <div class="col-sm-12 col-md-12 mb-1">
                                <label for="password2" class="form-label">Email</label>
                                {{ form.password2 }}
                            </div>
                            <div class="d-grid gap-2 mt-3">
                                <button type="submit" class="btn btn-outline-success">Registrar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
    
        
</div>


{% endblock content %}