blog/applications/entrada/urls.py
from django.urls import path
from . import views

app_name = "entrada_app"

urlpatterns = [
    path('entradas/', views.EntryListView.as_view(), name='entry-list'),
    path('entradas/<slug>/', views.EntryDetailView.as_view(), name='entry-detail')
]

blog/applications/favoritos/urls.py
from django.urls import path
from . import views

app_name = "favoritos_app"

urlpatterns = [
    path('perfil/', views.UserFavoriteView.as_view(), name='perfil'),
    path('perfil/<int:id>/', views.AddFavoriteView.as_view(), name='add-favorite'),
    path('perfil/delete-favorite/<int:id>/', views.FavoritesDeteleView.as_view(), name='delete-favorite')
]

blog/blog/urls.py
"""
Proyecto Curso Django
"""
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from applications.home.sitemap import EntrySitemap, Sitemap

urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entrada.urls')),
    re_path('', include('applications.favoritos.urls')),
    #URLS CKEDITOR
    path(r'^ckedtior/', include('ckeditor_uploader.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

sitemaps = {

    'site': Sitemap(
        [
            'home_app:index'
        ]
    ),
    'entradas': EntrySitemap
}

urlpatterns_sitemap = [

    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')

]

urlpatterns = urlpatterns_main + urlpatterns_sitemap

blog/applications/entrada/models.py
from datetime import timedelta, datetime
from django.db import models
from applications.users.models import User
from django.template.defaultfilters import slugify
from django.urls import reverse_lazy

#MANAGERS
from .managers import EntryManager



#APPS DE TERCEROS
from model_utils.models import TimeStampedModel
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
class Category(TimeStampedModel):

    short_name = models.CharField('Nombre Corto', max_length=15, unique=True)
    name = models.CharField('Nombre', max_length=30)

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

    def __str__(self):
        return self.name
    

class Tag(TimeStampedModel):

    name = models.CharField('Nombre', max_length=30)

    class Meta:
        verbose_name = 'Etiqueta'
        verbose_name_plural = 'Tags'

    def __str__(self):
        return self.name


class Entry(TimeStampedModel):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag)
    title = models.CharField('Titulo', max_length=200)
    resume = models.TextField('Resumen')
    content = RichTextUploadingField('Contenido')
    public = models.BooleanField(default=False)
    image = models.ImageField('Imagen', upload_to='Entry')
    portada = models.BooleanField(default=False)
    in_home = models.BooleanField(default=False)
    slug = models.SlugField(editable=False, max_length=300)
    objects = EntryManager()

    class Meta:
        verbose_name = 'Entrada'
        verbose_name_plural = 'Entradas'

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse_lazy('entrada_app:entry-datail', kwargs={'slug':self.slug})
    
    def save(self, *args, **kwargs):
        #CALCULAMOS LA HORA ACTUAL
        now = datetime.now()
        total_time = timedelta(hours=now.hour, minutes=now.minute, seconds=now.second)
        seconds = int(total_time.total_seconds())
        slug_unique = '%s %s' % (self.title, str(seconds))
        self.slug = slugify(slug_unique)

        super(Entry, self).save(*args, **kwargs)

blog/applications/entrada/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from .models import Entry, Category

class EntryListView(ListView):

    template_name = "entrada/lista.html"
    context_object_name = "entradas"
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super(EntryListView, self).get_context_data(**kwargs)

        if self.request.GET.get('kword', ''):
            context["busqueda"] = self.request.GET.get('kword', '')
        else:
            context["busqueda"] = self.request.GET.get('categoria', '')
        

        context["categorias"] = Category.objects.all()
        return context

    def get_queryset(self):

        kword = self.request.GET.get('kword', '')
        categoria = self.request.GET.get('categoria', '')
        #BUSQUEDA
        resultado = Entry.objects.buscar_entrada(kword, categoria)
        return resultado
    
class EntryDetailView(DetailView):

    model = Entry
    template_name = "entrada/detail.html"
    context_object_name = "entrada"

    # def get_object(self):
    #     id = self.kwargs.get("id")
    #     return Entry.objects.get(id=id)

blog/templates/entrada/base_entrada.html
{% extends "base.html" %}

{% load  static %}

{% block css %}

{% endblock css %}

{% block js %}

{% endblock js %}

blog/templates/entrada/detail.html
{% extends "entrada/base_entrada.html" %}

{% load static %}


{% block content %}

<div class="container">
    <h4>{{ entrada.title }} </h4>
    <hr>
    <h6>Categoria: {{ entrada.category }}</h6>
    <h6>Tags: {% for tag in entrada.tag.all %} <span class="badge bg-info text-white" style="font-size: 10px;">{{ tag }}</span> {% endfor %}</h6>
    <div class="row mb-5 mt-2">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header bg-info text-white">
                    Resumen
                </div>
                <div class="card-body">
                    <p class="card-text">{{ entrada.resume }}</p>
                </div>
            </div>
            <p>{{ entrada.content|safe }}</p>
        </div>
        <div class="col-md-4">
            <div class="card">
                <img src="{{ entrada.image.url }}" class="img-fluid" alt="...">
                <div class="card-body">
                    <form method="post" action="{% url 'favoritos_app:add-favorite' entrada.id %}">
                        {% csrf_token %}
                        <center><button type="submit" class="btn btn-outline-success btn-sm">Agregar Favoritos</button></center>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% include "includes/formulario-contacto.html" %}

{% endblock content %}

blog/templates/entrada/lista.html
{% extends "entrada/base_entrada.html" %}

{% load static %}


{% block content %}

<div class="container">
    <div class="row mb-5">
        <div class="col-md-9">
            <form method="get">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <input type="text" class="form-control" name="kword" id="kword" placeholder="Buscar">
                    <button class="btn btn-outline-success" type="submit">Buscar</button>
                </div>
            </form>
            <div class="row">

                {% if busqueda %}

                    <h6>Filtro busqueda: {{ busqueda }} </h6>

                {% endif %}

                {% for entrada in entradas %}
                    <div class="col-md-4 mb-3">
                        <div class="card">
                            <img src="{{ entrada.image.url }}" style="height: 14rem;" class="card-img-top">
                            <div class="card-body">
                                <a href="{% url 'entrada_app:entry-detail' entrada.slug %}"><h5 class="card-title">{{ entrada.title|truncatechars:20 }}</h5></a>
                                <p class="card-text">{{ entrada.resume|truncatechars:30 }}</p>
                            </div>
                        </div>
                    </div>

                {% empty %}

                <div class="col-md-12">

                    <div class="alert alert-warning" role="alert">
                        No hay resultados.
                    </div>

                </div>
                
                {% endfor %}
            </div>

            {% if is_paginated  %}

                <nav aria-label="Page navigation">
                    <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                        <li class="page-item ">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1">&laquo;</a>
                        </li>
                    {% endif %}
                    {% for i in paginator.page_range %}
                        <li class="page-item {% if page_obj.number == i %}active{% endif %}">
                            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                        </li>
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item ">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1">&raquo;</a>
                        </li>
                    {% endif %}
                    </ul>
                </nav>

            {% endif %}

        </div>
        <div class="col-md-3">
            <h5>Categorias</h5>
            <ul class="nav flex-column">

                <li class="nav-item mb-2"><a href="{% url 'entrada_app:entry-list' %}">Todos</a></li>

                {% for categoria in categorias %}

                <li class="nav-item mb-2"><a href="?categoria={{ categoria.short_name }}">{{ categoria.name }}</a></li>
                
                {% endfor %}

            </ul>
        </div>

    </div>
</div>

{% include "includes/formulario-contacto.html" %}

{% endblock content %}