blog/applications/entrada/urls.py
from django.urls import path
from . import views

app_name = "entrada_app"

urlpatterns = [
    path('entradas/', views.EntryListView.as_view(), name='entry-list'),
    path('entradas/<slug>/', views.EntryDetailView.as_view(), name='entry-detail')
]

blog/applications/favoritos/urls.py
from django.urls import path
from . import views

app_name = "favoritos_app"

urlpatterns = [
    path('perfil/', views.UserFavoriteView.as_view(), name='perfil'),
    path('perfil/<int:id>/', views.AddFavoriteView.as_view(), name='add-favorite'),
    path('perfil/delete-favorite/<int:id>/', views.FavoritesDeteleView.as_view(), name='delete-favorite')
]

blog/applications/users/urls.py
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user-register'),
    path('login/', views.LoginUser.as_view(), name='user-login'),
    path('logout/', views.LogoutView.as_view(), name='user-logout'),
    path('update/', views.UpdatePasswordView.as_view(), name='user-update')
]

blog/blog/urls.py
"""
Proyecto Curso Django
"""
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from applications.home.sitemap import EntrySitemap, Sitemap

urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entrada.urls')),
    re_path('', include('applications.favoritos.urls')),
    #URLS CKEDITOR
    path(r'^ckedtior/', include('ckeditor_uploader.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

sitemaps = {

    'site': Sitemap(
        [
            'home_app:index'
        ]
    ),
    'entradas': EntrySitemap
}

urlpatterns_sitemap = [

    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')

]

urlpatterns = urlpatterns_main + urlpatterns_sitemap

blog/applications/favoritos/models.py
from django.db import models
from applications.users.models import User
from applications.entrada.models import Entry
from .managers import FavoritesManager

#APPS DE TERCEROS
from model_utils.models import TimeStampedModel

# Create your models here.
class Favorites(TimeStampedModel):

    user = models.ForeignKey(User, related_name='user_favorites', on_delete=models.CASCADE)
    entry = models.ForeignKey(Entry, related_name='entry_favorites', on_delete=models.CASCADE)
    objects = FavoritesManager()


    class Meta:
        unique_together = ['user', 'entry']
        verbose_name = 'Entrada Favorita'
        verbose_name_plural = 'Entradas Favoritas'

    def __str__(self):
        return self.entry.title

blog/applications/favoritos/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.views.generic import ListView
from django.views.generic.edit import DeleteView
from django.views import View
from .models import Favorites
from applications.entrada.models import Entry

class UserFavoriteView(LoginRequiredMixin, ListView):

    template_name = "favoritos/perfil.html"
    context_object_name = "entradas_user"
    login_url = reverse_lazy('users_app:user-login')

    def get_queryset(self):
        return Favorites.objects.entradas_user(self.request.user)
    

class AddFavoriteView(LoginRequiredMixin, View):

    login_url = reverse_lazy('users_app:user-login')

    def post(self, request, *args, **kwargs):
        #RECUPERAR USUARIO
        usuario = self.request.user
        #RECUPERAR ENTRADA
        entrada = Entry.objects.get(id = self.kwargs['id'])

        if not Favorites.objects.filter(user=usuario, entry=entrada):

            Favorites.objects.create(
                user=usuario,
                entry=entrada
            )

            return HttpResponseRedirect(reverse_lazy('favoritos_app:perfil'))
        
        else:

            print(f'La relacion ya existe.')
            return HttpResponseRedirect(reverse_lazy('favoritos_app:perfil'))

    

class FavoritesDeteleView(DeleteView):

    model = Favorites
    success_url = reverse_lazy('favoritos_app:perfil')

    def get_object(self):
        id = self.kwargs.get("id")
        return Favorites.objects.get(id=id)

blog/templates/favoritos/base_favoritos.html
{% extends "base.html" %}

{% load  static %}

{% block css %}

{% endblock css %}

{% block js %}

{% endblock js %}

blog/templates/favoritos/perfil.html
{% extends "favoritos/base_favoritos.html" %}

{% load static %}


{% block content %}

<div class="container">
    <div class="row mb-5">
        <div class="col-md-4">
            <div class="card shadow-sm mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ user.full_name}}</h5>
                    <p class="card-text">
                        Correo: {{ user.email }}
                        <br>
                        Ocupacion: {{ user.ocupation }}
                        <br>
                        Fecha Nacimiento: {{ user.date_birth }}
                    </p>
                    <a href="" class="btn btn-outline-primary">Editar Datos</a>
                    <a href="{% url 'users_app:user-logout' %}" class="btn btn-outline-danger">Salir</a>
                </div>
            </div>
        </div>
        <div class="col-md-8">

            {% for entrada in entradas_user %}

            <div class="card shadow-sm mb-3">
                <div class="row g-0">
                    <div class="col-md-4">
                        <img src="{{ entrada.entry.image.url }}" style="height: 200px;" class="img-fluid rounded-start" alt="{{ entrada.entry.title }}">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">{{ entrada.entry.title }}</h5>
                            <p class="card-text">{{ entrada.entry.resume|truncatechars:100 }}</p>
                            <form method="post" action="{% url 'favoritos_app:delete-favorite' entrada.id %}">
                                <a href="{% url 'entrada_app:entry-detail' entrada.entry.id %}" class="btn btn-outline-info">Ver</a>
                                {% csrf_token %}
                                <button type="submit" class="btn btn-outline-danger">Eliminar</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            {% endfor %}
        </div>
    </div>
</div>

{% include "includes/formulario-contacto.html" %}

{% endblock content %}